export const ADMIN_CONTENT_ORDER = ['publications', 'news', 'events', 'media']

export const ADMIN_CONTENT_CONFIG = {
  publications: {
    label: 'Publications',
    singular: 'Publication',
    directory: 'publications',
    description: 'Research papers, reports, policy briefs, and toolkits.',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', helper: 'Optional. Auto-generated from the title if left blank.' },
      { name: 'category', label: 'Category', type: 'select', required: true, options: ['Research Paper', 'Policy Brief', 'Report', 'Toolkit', 'Working Paper'] },
      { name: 'author', label: 'Author', type: 'text', required: true },
      { name: 'date', label: 'Publish Date', type: 'date', required: true },
      { name: 'tags', label: 'Tags', type: 'tags', helper: 'Comma-separated tags.' },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea', rows: 4, required: true },
      { name: 'downloadUrl', label: 'Download URL', type: 'text', helper: 'Public path or external URL.' },
      { name: 'featured', label: 'Featured', type: 'checkbox' },
      { name: 'content', label: 'Body', type: 'markdown', rows: 18, required: true },
    ],
    defaults: {
      title: '',
      slug: '',
      category: 'Research Paper',
      author: '',
      date: '',
      tags: '',
      excerpt: '',
      downloadUrl: '',
      featured: false,
      content: '',
    },
    listSummary: ['category', 'date'],
  },
  news: {
    label: 'News',
    singular: 'Article',
    directory: 'news',
    description: 'News stories, blogs, press releases, and media updates.',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', helper: 'Optional. Auto-generated from the title if left blank.' },
      { name: 'category', label: 'Category', type: 'select', required: true, options: ['Press Release', 'Blog', 'In The Media', 'Event Report'] },
      { name: 'author', label: 'Author', type: 'text', required: true },
      { name: 'date', label: 'Publish Date', type: 'date', required: true },
      { name: 'image', label: 'Image URL', type: 'text', helper: 'Optional remote image URL or public path.' },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea', rows: 4, required: true },
      { name: 'featured', label: 'Featured', type: 'checkbox' },
      { name: 'content', label: 'Body', type: 'markdown', rows: 18, required: true },
    ],
    defaults: {
      title: '',
      slug: '',
      category: 'Press Release',
      author: '',
      date: '',
      image: '',
      excerpt: '',
      featured: false,
      content: '',
    },
    listSummary: ['category', 'date'],
  },
  events: {
    label: 'Events',
    singular: 'Event',
    directory: 'events',
    description: 'Conferences, workshops, webinars, and training events.',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', helper: 'Optional. Auto-generated from the title if left blank.' },
      { name: 'type', label: 'Type', type: 'select', required: true, options: ['Conference', 'Workshop', 'Webinar', 'Training'] },
      { name: 'date', label: 'Start Date', type: 'date', required: true },
      { name: 'endDate', label: 'End Date', type: 'date' },
      { name: 'location', label: 'Location', type: 'text', required: true },
      { name: 'status', label: 'Status', type: 'select', required: true, options: ['upcoming', 'past'] },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea', rows: 4, required: true },
      { name: 'featured', label: 'Featured', type: 'checkbox' },
      { name: 'content', label: 'Body', type: 'markdown', rows: 16, required: true },
    ],
    defaults: {
      title: '',
      slug: '',
      type: 'Conference',
      date: '',
      endDate: '',
      location: '',
      status: 'upcoming',
      excerpt: '',
      featured: false,
      content: '',
    },
    listSummary: ['type', 'date'],
  },
  media: {
    label: 'Media Kit',
    singular: 'Media Asset',
    directory: 'media',
    description: 'Downloadable media assets shown on the media page.',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', helper: 'Optional. Auto-generated from the title if left blank.' },
      { name: 'date', label: 'Publish Date', type: 'date', required: true },
      { name: 'type', label: 'Asset Type', type: 'text', required: true, helper: 'Examples: PDF, SVG, ZIP.' },
      { name: 'size', label: 'File Size', type: 'text', required: true, helper: 'Examples: 4.8 MB, 520 KB.' },
      { name: 'assetUrl', label: 'Asset URL', type: 'text', helper: 'Public path or external download URL. Leave blank to hide download.' },
      { name: 'excerpt', label: 'Description', type: 'textarea', rows: 4 },
      { name: 'featured', label: 'Featured', type: 'checkbox' },
      { name: 'content', label: 'Notes', type: 'markdown', rows: 10 },
    ],
    defaults: {
      title: '',
      slug: '',
      date: '',
      type: 'PDF',
      size: '',
      assetUrl: '',
      excerpt: '',
      featured: false,
      content: '',
    },
    listSummary: ['type', 'date'],
  },
}

export function getAdminContentConfig(type) {
  return ADMIN_CONTENT_CONFIG[type] || null
}

export function getAdminContentTypes() {
  return ADMIN_CONTENT_ORDER.map((type) => ({
    type,
    ...ADMIN_CONTENT_CONFIG[type],
  }))
}
